services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: TestDatabase
    ports:
      - "5433:5432"
    networks:
      - test-network
    volumes:
      - ./TheatreCenter.UnitTests/Tests/Database/schemas:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d TestDatabase"]
      interval: 5s
      timeout: 3s
      retries: 5

  unit-test-runner:
    build:
      context: .  
      dockerfile: Dockerfile
    networks:
      - test-network
    working_dir: /src
    command: ["/run-unit-tests.sh"]
    volumes:
      - ./TheatreCenter.UnitTests/unit-test-results:/test-results


  integration-test-runner:
    build:
      context: .  
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    networks:
      - test-network
    working_dir: /src
    environment:
      DB_CONNECTION_STRING: "Host=db;Port=5432;Database=TestDatabase;Username=postgres;Password=postgres"
    command: ["/run-integration-tests.sh"]
    volumes:
      - ./TheatreCenter.UnitTests/integration-test-results:/test-results

  e2e-test-runner:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    networks:
      - test-network
    working_dir: /src
    environment:
      DB_CONNECTION_STRING: "Host=db;Port=5432;Database=TestDatabase;Username=postgres;Password=postgres"
    command: ["/run-e2e-tests.sh"]
    volumes:
      - ./TheatreCenter.UnitTests/e2e-test-results:/test-results
 

networks:
  test-network:
    driver: bridge