// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TheatreCenter.Data;

#nullable disable

namespace TheatreCenter.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AccountActorFavorite", b =>
                {
                    b.Property<int>("AccountId")
                        .HasColumnType("integer");

                    b.Property<int>("ActorId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("AccountId", "ActorId");

                    b.HasIndex("ActorId");

                    b.ToTable("AccountActorFavorites");
                });

            modelBuilder.Entity("AccountMusicalFavorite", b =>
                {
                    b.Property<int>("AccountId")
                        .HasColumnType("integer");

                    b.Property<int>("MusicalId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("AccountId", "MusicalId");

                    b.HasIndex("MusicalId");

                    b.ToTable("AccountMusicalFavorites");
                });

            modelBuilder.Entity("AccountTheatreFavorite", b =>
                {
                    b.Property<int>("AccountId")
                        .HasColumnType("integer");

                    b.Property<int>("TheatreId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("AccountId", "TheatreId");

                    b.HasIndex("TheatreId");

                    b.ToTable("AccountTheatreFavorites");
                });

            modelBuilder.Entity("TheatreCenter.Domain.Models.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AccessLevel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("LastFavoritesViewDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("UpgradeRequest")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("TheatreCenter.Domain.Models.Actor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AddInfo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int>("Height")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("VoiceType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Weight")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Actors");
                });

            modelBuilder.Entity("TheatreCenter.Domain.Models.ActorRole", b =>
                {
                    b.Property<int>("ActorId")
                        .HasColumnType("integer");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("ActorId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("ActorRoles");
                });

            modelBuilder.Entity("TheatreCenter.Domain.Models.CastMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ActorId")
                        .HasColumnType("integer");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<int>("ShowId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ActorId");

                    b.HasIndex("RoleId");

                    b.HasIndex("ShowId");

                    b.ToTable("CastMembers");
                });

            modelBuilder.Entity("TheatreCenter.Domain.Models.Musical", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AgeRestriction")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("interval");

                    b.Property<int>("TheatreId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.HasIndex("TheatreId");

                    b.ToTable("Musicals");
                });

            modelBuilder.Entity("TheatreCenter.Domain.Models.MusicalTheme", b =>
                {
                    b.Property<int>("MusicalId")
                        .HasColumnType("integer");

                    b.Property<int>("ThemeId")
                        .HasColumnType("integer");

                    b.HasKey("MusicalId", "ThemeId");

                    b.HasIndex("ThemeId");

                    b.ToTable("MusicalThemes");
                });

            modelBuilder.Entity("TheatreCenter.Domain.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("MusicalId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("RoleType")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)");

                    b.HasKey("Id");

                    b.HasIndex("MusicalId");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("TheatreCenter.Domain.Models.Show", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MusicalId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Date");

                    b.HasIndex("MusicalId");

                    b.ToTable("Shows");
                });

            modelBuilder.Entity("TheatreCenter.Domain.Models.Theatre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AddInfo")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Theatres");
                });

            modelBuilder.Entity("TheatreCenter.Domain.Models.Theme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Themes");
                });

            modelBuilder.Entity("AccountActorFavorite", b =>
                {
                    b.HasOne("TheatreCenter.Domain.Models.Account", "Account")
                        .WithMany("FavoriteActors")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TheatreCenter.Domain.Models.Actor", "Actor")
                        .WithMany()
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Actor");
                });

            modelBuilder.Entity("AccountMusicalFavorite", b =>
                {
                    b.HasOne("TheatreCenter.Domain.Models.Account", "Account")
                        .WithMany("FavoriteMusicals")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TheatreCenter.Domain.Models.Musical", "Musical")
                        .WithMany()
                        .HasForeignKey("MusicalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Musical");
                });

            modelBuilder.Entity("AccountTheatreFavorite", b =>
                {
                    b.HasOne("TheatreCenter.Domain.Models.Account", "Account")
                        .WithMany("FavoriteTheatres")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TheatreCenter.Domain.Models.Theatre", "Theatre")
                        .WithMany()
                        .HasForeignKey("TheatreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Theatre");
                });

            modelBuilder.Entity("TheatreCenter.Domain.Models.ActorRole", b =>
                {
                    b.HasOne("TheatreCenter.Domain.Models.Actor", "Actor")
                        .WithMany("ActorRoles")
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TheatreCenter.Domain.Models.Role", "Role")
                        .WithMany("ActorRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Actor");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("TheatreCenter.Domain.Models.CastMember", b =>
                {
                    b.HasOne("TheatreCenter.Domain.Models.Actor", "Actor")
                        .WithMany("CastMembers")
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TheatreCenter.Domain.Models.Role", "Role")
                        .WithMany("CastMembers")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TheatreCenter.Domain.Models.Show", "Show")
                        .WithMany("CastMembers")
                        .HasForeignKey("ShowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Actor");

                    b.Navigation("Role");

                    b.Navigation("Show");
                });

            modelBuilder.Entity("TheatreCenter.Domain.Models.Musical", b =>
                {
                    b.HasOne("TheatreCenter.Domain.Models.Theatre", "Theatre")
                        .WithMany("Musicals")
                        .HasForeignKey("TheatreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Theatre");
                });

            modelBuilder.Entity("TheatreCenter.Domain.Models.MusicalTheme", b =>
                {
                    b.HasOne("TheatreCenter.Domain.Models.Musical", "Musical")
                        .WithMany("MusicalThemes")
                        .HasForeignKey("MusicalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TheatreCenter.Domain.Models.Theme", "Theme")
                        .WithMany("MusicalThemes")
                        .HasForeignKey("ThemeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Musical");

                    b.Navigation("Theme");
                });

            modelBuilder.Entity("TheatreCenter.Domain.Models.Role", b =>
                {
                    b.HasOne("TheatreCenter.Domain.Models.Musical", "Musical")
                        .WithMany("Roles")
                        .HasForeignKey("MusicalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Musical");
                });

            modelBuilder.Entity("TheatreCenter.Domain.Models.Show", b =>
                {
                    b.HasOne("TheatreCenter.Domain.Models.Musical", "Musical")
                        .WithMany("Shows")
                        .HasForeignKey("MusicalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Musical");
                });

            modelBuilder.Entity("TheatreCenter.Domain.Models.Account", b =>
                {
                    b.Navigation("FavoriteActors");

                    b.Navigation("FavoriteMusicals");

                    b.Navigation("FavoriteTheatres");
                });

            modelBuilder.Entity("TheatreCenter.Domain.Models.Actor", b =>
                {
                    b.Navigation("ActorRoles");

                    b.Navigation("CastMembers");
                });

            modelBuilder.Entity("TheatreCenter.Domain.Models.Musical", b =>
                {
                    b.Navigation("MusicalThemes");

                    b.Navigation("Roles");

                    b.Navigation("Shows");
                });

            modelBuilder.Entity("TheatreCenter.Domain.Models.Role", b =>
                {
                    b.Navigation("ActorRoles");

                    b.Navigation("CastMembers");
                });

            modelBuilder.Entity("TheatreCenter.Domain.Models.Show", b =>
                {
                    b.Navigation("CastMembers");
                });

            modelBuilder.Entity("TheatreCenter.Domain.Models.Theatre", b =>
                {
                    b.Navigation("Musicals");
                });

            modelBuilder.Entity("TheatreCenter.Domain.Models.Theme", b =>
                {
                    b.Navigation("MusicalThemes");
                });
#pragma warning restore 612, 618
        }
    }
}
